### ISSUE TITLE
Nim SDL2 Game Development for Beginners #1 Setup and your first moving image

### ISSUE THREAD

**Issue by Kiloneie** [nim-lang/edutainment#1]
In this video i will show setting up SDL2 and going trough the basics of understanding how to initialize SDL2, what everything does and works with the end result of this first video being showing a window with some moving image, and viewers understanding how we got there, be able to easily reproduce the contents of the video.

**Comment by planetis-m** [comment]
@Kiloneie see https://www.youtube.com/watch?v=yFLa3ln16w0 for inspiration. It's excellent.

**Comment by planetis-m** [comment]
Also an idiomatic api on top of nim-lang/SDL2 would be nice...

**Comment by Kiloneie** [comment]
Finally after a long time of being busy with work and not finding the time, the video is finally done: https://youtu.be/x76fT8GG0Pk
