### ISSUE TITLE
Nim for Beginners #26 Reference Objects

### ISSUE THREAD

**Issue by Kiloneie** [nim-lang/edutainment#3]
In this video i will teach the viewer about reference objects in depth which i have touched upon and briefly explained in the "Nim SDL2 Game Development for Beginners #1 Setup and your first moving image" video.

Some of the chapters of the this video will be the following(i may change this before completion if i find that there will be too much information for the viewer in a single video):

- What are reference objects ?
- Reference object use cases
- Brief explanation of Nim's default memory management(full explanation will be in a separate video)
- Values created on the stack
- Values created on the heap
- A chapter showcasing the differences and use cases of normal/plain objects vs reference objects

**Comment by Araq** [comment]
You should focus on `--gc:orc` and not on the "default memory management".

**Comment by Kiloneie** [comment]
Of course, that was my bad on writing this issue which i started about a year ago and i kinda copy pasted that part.

I will be releasing/sharing this video as private before it goes live to ensure the correctness of the content of this one(probably standard procedure from now on).

**Comment by Araq** [comment]
You don't have to go too much into the details but the code should compile with `--gc:orc` and probably you should mention `.acyclic` and `.cursor` annotations as these are crucial for performance.

**Comment by Kiloneie** [comment]
Okay the video is made, a few finishing touches left remain such as the video's contents/chapters compilation/showcase at the beginning of the video(i think i will simply rapid fire trough the timestamps of the video where the chapter begins), thumbnail, timestamps and maybe some highlights/zoom where needed, maybe for the console output.

This video will be unlisted on YT until i get some feedback in order to fix potential mistakes of the contents and any other problems.

LINK: https://youtu.be/ir-bRvDMBu0

**Comment by Kiloneie** [comment]
Video is now finished(got some feedback on Nim Forum): https://youtu.be/kkSAVKKIoVc
